import { useEffect, useState } from "react";
import type { CoordinatesType } from "../../../types";
import {
  COLUMNS_HEADER,
  ROWS_HEADER,
  transformLetterToNumber,
} from "../../../utils/game";
import ErrorMessage from "../ErrorMessage";

type InputType = {
  inputColumn: string;
  inputRow: string;
};

type ErrorType = {
  columnCriteria: boolean;
  rowCriteria: boolean;
  emptyField: boolean;
};

interface IFireControl {
  target: CoordinatesType | [0, 0];
  setTarget: React.Dispatch<React.SetStateAction<CoordinatesType>>;
  handleFire: () => void;
}

const initialValues: InputType = {
    inputColumn: "",
    inputRow: "",
  }

function FireControl({ target, setTarget, handleFire }: IFireControl) {
  const [value, setValue] = useState<InputType>(initialValues);
  const [errors, setErrors] = useState<ErrorType>({
    columnCriteria: false,
    rowCriteria: false,
    emptyField: false,
  });

  function handleChange(e: React.FormEvent<HTMLInputElement>): void {
    const { name, value: newValue } = e.currentTarget;
    if (newValue.length === 0) {
      const updated = { ...value, [name]: newValue };
      setValue(updated);
      setTarget([
        transformLetterToNumber(updated.inputColumn),
        updated.inputRow ? parseInt(updated.inputRow) : 0,
      ]);
      return;
    }
    if (name === "inputColumn") {
      const upperValue = newValue.toUpperCase();
      if (COLUMNS_HEADER.includes(upperValue)) {
        const updated = { ...value, inputColumn: upperValue };
        setValue(updated);
        setErrors((prev) => ({
          ...prev,
          columnCriteria: false,
        }));
        setTarget([
          transformLetterToNumber(updated.inputColumn),
          updated.inputRow ? parseInt(updated.inputRow) : 0,
        ]);
      } else {
        setErrors((prev) => ({
          ...prev,
          columnCriteria: true,
        }));
      }
      return;
    }

    if (name === "inputRow") {
      // Generated by GPT: reg. exp. allows only numeric input
      if (/^\d+$/.test(newValue) && ROWS_HEADER.includes(parseInt(newValue))) {
        const updated = { ...value, inputRow: newValue };
        setValue(updated);
        setErrors((prev) => ({
          ...prev,
          rowCriteria: false,
        }));
        setTarget([
          transformLetterToNumber(updated.inputColumn),
          updated.inputRow ? parseInt(updated.inputRow) : 0,
        ]);
      } else {
        setErrors((prev) => ({
          ...prev,
          rowCriteria: true,
        }));
      }
      return;
    }
  }

  useEffect(() => {
    if (target[0] === 0 && target[1] === 0) setValue(initialValues)
  }, [target])

  function handleClick() {
    if (value.inputColumn.length > 0 && value.inputRow.length > 0) {
      handleFire();
      setErrors((prev) => ({
        ...prev,
        emptyField: false,
      }));
    } else {
      setErrors((prev) => ({
        ...prev,
        emptyField: true,
      }));
    }
  }

  return (
    <div className='flex flex-col gap-10 w-52 h-full'>
      <div className='flex gap-2 items-center justify-between'>
        <div className='flex gap-4 h-12'>
          <input
            name='inputColumn'
            value={value?.inputColumn}
            placeholder='A'
            className='w-10 h-full border-b-2 text-center placeholder:text-center'
            onChange={(e) => handleChange(e)}
          />
          <input
            name='inputRow'
            value={value?.inputRow}
            placeholder='5'
            className='w-10 h-full border-b-2 text-center placeholder:text-center'
            onChange={(e) => handleChange(e)}
          />
        </div>
        <button type='button' className='w-24 h-12' onClick={handleClick}>
          Fire!
        </button>
      </div>
      <div className='w-full h-60 grid grid-col-3 justify-between gap-1'>
        {errors.emptyField && (
          <ErrorMessage message='You must fill both coordinates!' />
        )}
        {errors.columnCriteria && (
          <ErrorMessage message='The input can only be from A to J!' />
        )}
        {errors.rowCriteria && (
          <ErrorMessage message='The input can only be from 1 to 10!' />
        )}
      </div>
    </div>
  );
}

export default FireControl;
